language: java

jdk:
  - openjdk7
  - oraclejdk7

before_install:
 - sudo add-apt-repository -y ppa:groovy-dev/grails
 - sudo apt-get update
 - sudo apt-get -y install grails-ppa
 - sudo apt-get install grails-1.3.7 # or the grails version.

script: grails clean package-plugin

